### ISSUE TITLE
.NET 7.0 - PR created

### ISSUE THREAD

**Issue by 274188A** [tranpl/redcap-api#114]
Thanks for this contribution - really nice.

Is there a reason why the library is using `netstandard2.1`?  I crated a [fork](https://github.com/cctrbic/redcap-api/pull/115) to move onto .net7.0.

Thanks again!

**Comment by tranpl** [comment]
PR completed, master updated to net7

**Comment by tranpl** [comment]
> Thanks for this contribution - really nice.
> 
> Is there a reason why the library is using `netstandard2.1`? I crated a [fork](https://github.com/cctrbic/redcap-api/pull/115) to move onto .net7.0.
> 
> Thanks again!

Project started with netstandard 2 i think, been a while but I would like it to be updated. .Net8 next =)
