### ISSUE TITLE
ExportRecordsAsync in csv uses the rawOrLabelHeaders instead of rawOrLabel

### ISSUE THREAD

**Issue by jlewis99** [tranpl/redcap-api#122]
ExportRecordsAsync in csv uses the rawOrLabelHeaders instead of rawOrLabel

lines 3250 and 3372 and 3487 in RedcapApi.cs

                // Pertains to CSV data only
                var _rawOrLabelValue = rawOrLabelHeaders.ToString();
                if (!IsNullOrEmpty(_rawOrLabelValue))
                {
                    payload.Add("rawOrLabel", _rawOrLabelValue);
                }
-------------------------------------------------------------------------------------
should be:
-------------------------------------------------------------------------------------
                // Pertains to CSV data only
                var _rawOrLabelValue = rawOrLabel.ToString();
                if (!IsNullOrEmpty(_rawOrLabelValue))
                {
                    payload.Add("rawOrLabel", _rawOrLabelValue);
                }

**Comment by tranpl** [comment]
Thanks @jlewis99,  will have it ready in 1.3.5
