### ISSUE TITLE
The brain 'main' seem to be missing background process param

### ISSUE THREAD

**Issue by 274188A** [tranpl/redcap-api#133]
the 'main' branch seems to be missing the background process param.

also - i've always wondered why we have 2 ImportRedcordAsync methods...both exactly the same except for the content param on one.

**Comment by tranpl** [comment]
Hey @274188A , the signatures for these methods are different, they are overloads of the ImportRecordsAsync method. I think it could be something to consider removing in future versions and just keep the one with content type; prior versions didn't have Content Type.
