### ISSUE TITLE
Incorrect format for 'records' parameter in DeleteRecordsAsync

### ISSUE THREAD

**Issue by etfrenchvcu** [tranpl/redcap-api#58]
When calling DeleteRecordsAsync, I receive the following error message:
`Incorrect format for 'records' parameter. It must be passed as an array, even if it only contains a single record name.`
I think we're passing the REDCap API an invalid `records` parameter by converting the `string[] records` parameter  to a string. I think we could fix it by adding each record in the `records` array to the `payload` as an item in an array.

Instead of 
`payload.Add("records", await this.ConvertArraytoString(records));`

We could do the following, which would successfully delete the records.
```
for (var i = 0; i< records.Length; i++)
{
  payload.Add($"records[{i}]", records[i]);
}
```

**Comment by tranpl** [comment]
thanks @etfrenchvcu , updated with fix
