### ISSUE TITLE
Static references to _token and _uri prevent concurrent instantiations of RedcapApi

### ISSUE THREAD

**Issue by etfrenchvcu** [tranpl/redcap-api#70]
In Api/Redcap.cs, the properties _token and _uri are currently static. Because of this, if I try to create two instances of RedcapApi pointing to two distinct projects, the static properties of the first instance will be overwritten by the static properties of the second. In the example below, the _token value of rc1 will inadvertently be set to "foo". Since they are no public getters or setters on these private static properties, you should be able to fix the issue by removing the static keyword.

var rc1 = new RedcapApi("test", _redcapConfig.BaseApiUrl);
var rc2 = new RedcapApi("foo", _redcapConfig.BaseApiUrl);

**Comment by tranpl** [comment]
I'd recommend using the new constructor, e.g redcapApi = new RedcapApi(_redcapConfig.baseApiUrl);
Thew new method calls requires tokens to be passed. I deprecated the older methods without the token moving forward. This allows for more freedom of the api usage, but require extra param to be passed each time.
