### ISSUE TITLE
This package doesn't work from Nuget

### ISSUE THREAD

**Issue by JamesAAllsopp** [tranpl/redcap-api#85]
Include in console project  from Nuget ,v1.0.7  using Visual Studio 2015.

Creates Models folder, doesn't resolve references.

**Comment by cctrbic** [comment]
@EthicsGradient Could you provide your code snippet?

What references are you referring to? Here's a snippet that could help. This is a default, new console app created in visual studio 2019.
```csharp
using System;
using Redcap;
using Redcap.Models;
namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            var apiToken = "674189E39351B6EFC1E058EBB11DB8F9";
            var redcap_api = new RedcapApi("http://localhost:8080/redcap/api/");

            var version = redcap_api.ExportRedcapVersionAsync(apiToken, ReturnFormat.json).Result;
            Console.WriteLine("Version => " + version);
        }
    }
}
```
This is what the .csproj file looks like.
```csharp
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RedcapAPI" Version="1.0.7" />
  </ItemGroup>

</Project>
```

**Comment by JamesAAllsopp** [comment]
My mistake I was trying to use the library in an old .net 4.5 project rather than .net core, so it works once I've done that. 

Another problem is that the nuget package is out of date with respect to the repository and needs building.

**Comment by tranpl** [comment]
I'll go ahead and update the nuget package. Thanks for the update.
