### ISSUE TITLE
isLargeDataset is never used, and possibly causing "" response from anything but small imports

### ISSUE THREAD

**Issue by dr01d3r** [tranpl/redcap-api#86]
https://github.com/cctrbic/redcap-api/blob/5d3ed427af7084635ddd723ff1176c0ec529a485/RedcapApi/Utilities/Utils.cs#L675

I haven't pulled it down to test local changes, but I think this is preventing my programmers from gracefully importing data.  The workaround has been to reduce the dataset until it works.

I'll come back to this when I've had time to fork it and test.

**Comment by dr01d3r** [comment]
@tranpl I've done some initial testing on a solution that seems to work.  You can see the work-in-progress in my [forked repo](https://github.com/dr01d3r/redcap-api/commit/cd0b7c752b594b10fabfe2542add77db2e1b80ed).

The StringContent solution did not seem to work, and I believe it had to do with the content type of `application/json`.  I used the 2nd answer in that same SO post for this change.  In hind-sight, I probably should've tried to just change the content-type 1st and see what happened.  What do you think?

**Comment by tranpl** [comment]
@dr01d3r , thanks for sharing. I'll take a look at it and add it asap. Thanks!

**Comment by dr01d3r** [comment]
Welcome back! :)

I actually implemented this and published it as a pre-release to a local nuget repo we have on-site, and haven't had any issues yet.  Once you're able to publish, we will update to pull in your official release.

**Comment by tranpl** [comment]
Awesome! I have been so busy with other projects; been wanting to add new features and fixes etc. Thank you for the contribution. Going to try a push today.

**Comment by cctrbic** [comment]
#87 @dr01d3r Thanks Chris. I'm releasing this patch as 1.0.8 =)
