### ISSUE TITLE
Update only field from a form associated to a record

### ISSUE THREAD

**Issue by dmarcicLIH** [tranpl/redcap-api#97]
Hi, 
Is it possible to update some fields of an identified record using this API as i don't see an update method ? 
Thanks
David

**Comment by tranpl** [comment]
Yes, you can update any fields in any form for projects which the redcap api token has access using this api library. I believe there are some sample code for exporting and importing of the meta data (data dictionary) for individual projects. You then update the dictionary as needed and import back into REDCap. 

This is the example from the RedcapApiDemo project in the source code.
`
var _uri = "http://localhost/redcap";
var redcap_api_2_0_0 = new RedcapApi(_uri);
 var ExportMetaDataAsyncResult = await redcap_api_2_0_0.ExportMetaDataAsync(_token, Content.MetaData, ReturnFormat.json, null, null, OnErrorFormat.json);
`
