### ISSUE TITLE
Use of static property in Redcap APi class

### ISSUE THREAD

**Issue by dmarcicLIH** [tranpl/redcap-api#99]
Hi, 
i would like to know why you use static property for RedCapApi object properties like 

`        /// <summary>

        /// Redcap API Uri
        /// Location of your redcap instance
        /// </summary>
        /// <example>
        /// https://localhost/redcap/api
        /// </example>
        private static Uri _uri;`

as we cannot use 2 instances in parallel within the same project as i have to communicates between 2 redcap servers instance?  The second object instanciation  always overwrite the first one. 
thanks David

**Comment by tranpl** [comment]
Thank you for the question. I have not been active on reading the issues. Its been so long, my initial thought was that users would have one API  instance going to one redcap instance. I think you are correct, you wouldn't be able to point to two different instances of REDCap in this case. I did not account for your use case =)

Lets see if we can make it more flexible in the next update.

**Comment by cctrbic** [comment]
1.3.1 has been updated to allow multiple instance of the API
